#!/usr/bin/env bash

set -euxo pipefail

destination_dir=$1

util_loc="/opt/resource/util.sh"

if [[ ! -f "${util_loc}" ]]; then
  util_loc="./util.sh"
fi

# shellcheck source=./util.sh
source ${util_loc}

input_json="$(cat)"
